/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import javax.swing.JOptionPane;

/**
 *
 * @author salom
 */
public class V2Menu extends javax.swing.JFrame {

    /**
     * Creates new form Ventana2
     */
    public V2Menu() {
        initComponents();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agregar_btn = new javax.swing.JLabel();
        Analizar_btn = new javax.swing.JLabel();
        Buscar_btn = new javax.swing.JLabel();
        Salir_btn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Agregar_btn.setForeground(new java.awt.Color(253, 130, 4));
        Agregar_btn.setText("                                                     .");
        Agregar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Agregar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Agregar_btnMouseClicked(evt);
            }
        });
        getContentPane().add(Agregar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 380, 80));

        Analizar_btn.setForeground(new java.awt.Color(253, 130, 4));
        Analizar_btn.setText("        .");
        Analizar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Analizar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Analizar_btnMouseClicked(evt);
            }
        });
        getContentPane().add(Analizar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 380, 80));

        Buscar_btn.setForeground(new java.awt.Color(253, 130, 4));
        Buscar_btn.setText("   .");
        Buscar_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Buscar_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buscar_btnMouseClicked(evt);
            }
        });
        getContentPane().add(Buscar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 380, 80));

        Salir_btn.setForeground(new java.awt.Color(255, 255, 255));
        Salir_btn.setText(".");
        Salir_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Salir_btnMouseClicked(evt);
            }
        });
        getContentPane().add(Salir_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 380, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Botones proyecto.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Al hacer click sobre el bot&oacute;n pasa a la ventana de agregar 
     * un resumen.
     * @param evt 
     */
    private void Agregar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Agregar_btnMouseClicked
        V3Agregar_Resumen v3 = new V3Agregar_Resumen();
        v3.setLocationRelativeTo(null);
        v3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Agregar_btnMouseClicked
    
    /**
     * Al hacer click sobre el bot&oacute;n pasa a la ventana 
     * de analizar resumen. 
     * @param evt 
     */
    private void Analizar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Analizar_btnMouseClicked
        V4Analizar v4 = new V4Analizar();
        v4.setLocationRelativeTo(null);
        v4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Analizar_btnMouseClicked
    
    /**
     * Al hacer click sobre el bot&oacute;n pasa a la ventana 
     * de buscar resumen.
     * @param evt 
     */
    private void Buscar_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscar_btnMouseClicked
        V5Buscar v5 = new V5Buscar();
        v5.setLocationRelativeTo(null);
        v5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Buscar_btnMouseClicked
    
    /**
     * Al hacer click sobre el bot&oacute;n se sale del programa.
     * @param evt 
     */
    private void Salir_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Salir_btnMouseClicked
        JOptionPane.showMessageDialog(null, "¡Gracias por su visita!");
        this.dispose();
    }//GEN-LAST:event_Salir_btnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V2Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V2Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V2Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V2Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V2Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agregar_btn;
    private javax.swing.JLabel Analizar_btn;
    private javax.swing.JLabel Buscar_btn;
    private javax.swing.JLabel Salir_btn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
